// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseManagement.ClientManagement.Infrastructure.DbContexts;

#nullable disable

namespace WarehouseManagement.ClientManagement.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250802175445_ClientManagement_Initial")]
    partial class ClientManagement_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("client-management")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarehouseManagement.ClientManagement.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("character varying(170)");

                    b.ComplexProperty<Dictionary<string, object>>("ArchivedAt", "WarehouseManagement.ClientManagement.Domain.Entities.Client.ArchivedAt#ArchivedAt", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime?>("Value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ArchivedAt");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("IsArchived", "WarehouseManagement.ClientManagement.Domain.Entities.Client.IsArchived#IsArchived", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Value")
                                .HasColumnType("boolean")
                                .HasColumnName("IsArchived");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "WarehouseManagement.ClientManagement.Domain.Entities.Client.Title#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Title");
                        });

                    b.HasKey("Id");

                    b.ToTable("Clients", "client-management");
                });
#pragma warning restore 612, 618
        }
    }
}
