// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseManagement.ResourceManagement.Infrastructure.DbContexts;

#nullable disable

namespace WarehouseManagement.ResourceManagement.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("resource-management")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarehouseManagement.ResourceManagement.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.ComplexProperty<Dictionary<string, object>>("ArchivedAt", "WarehouseManagement.ResourceManagement.Domain.Entities.Resource.ArchivedAt#ArchivedAt", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime?>("Value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ArchivedAt");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("IsArchived", "WarehouseManagement.ResourceManagement.Domain.Entities.Resource.IsArchived#IsArchived", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Value")
                                .HasColumnType("boolean")
                                .HasColumnName("IsArchived");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "WarehouseManagement.ResourceManagement.Domain.Entities.Resource.Title#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Title");
                        });

                    b.HasKey("Id");

                    b.ToTable("Resources", "resource-management");
                });
#pragma warning restore 612, 618
        }
    }
}
