// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseManagement.OutcomeProcessing.Infrastructure.DbContexts;

#nullable disable

namespace WarehouseManagement.OutcomeProcessing.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250807134715_OutcomeProcessing_Initial")]
    partial class OutcomeProcessing_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("outcome-processing")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarehouseManagement.OutcomeProcessing.Domain.Aggregates.OutcomeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.ComplexProperty<Dictionary<string, object>>("ClientId", "WarehouseManagement.OutcomeProcessing.Domain.Aggregates.OutcomeDocument.ClientId#ClientId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("ClientId");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("CreatedAt", "WarehouseManagement.OutcomeProcessing.Domain.Aggregates.OutcomeDocument.CreatedAt#CreatedAt", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("NumDocument", "WarehouseManagement.OutcomeProcessing.Domain.Aggregates.OutcomeDocument.NumDocument#NumDocument", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("NumDocument");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Status", "WarehouseManagement.OutcomeProcessing.Domain.Aggregates.OutcomeDocument.Status#OutcomeDocumentStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("Status");
                        });

                    b.HasKey("Id");

                    b.ToTable("OutcomeDocuments", "outcome-processing");
                });

            modelBuilder.Entity("WarehouseManagement.OutcomeProcessing.Domain.Entities.OutcomeResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("OutcomeDocumentId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("ResourceId", "WarehouseManagement.OutcomeProcessing.Domain.Entities.OutcomeResource.ResourceId#ResourceId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("ResourceId");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ResourceQuantity", "WarehouseManagement.OutcomeProcessing.Domain.Entities.OutcomeResource.ResourceQuantity#Quantity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("ResourceQuantity");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UnitId", "WarehouseManagement.OutcomeProcessing.Domain.Entities.OutcomeResource.UnitId#UnitId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("UnitId");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OutcomeDocumentId");

                    b.ToTable("OutcomeResources", "outcome-processing");
                });

            modelBuilder.Entity("WarehouseManagement.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "ProcessedAt")
                        .HasDatabaseName("idx_outbox_messages_unprocessed")
                        .HasFilter("\"ProcessedAt\" IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreatedAt", "ProcessedAt"), new[] { "Id", "Type", "Payload" });

                    b.ToTable("OutboxMessages", "outcome-processing");
                });

            modelBuilder.Entity("WarehouseManagement.OutcomeProcessing.Domain.Entities.OutcomeResource", b =>
                {
                    b.HasOne("WarehouseManagement.OutcomeProcessing.Domain.Aggregates.OutcomeDocument", null)
                        .WithMany("Resources")
                        .HasForeignKey("OutcomeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarehouseManagement.OutcomeProcessing.Domain.Aggregates.OutcomeDocument", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
