// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseManagement.BalanceManagement.Infrastructure.DbContexts;

#nullable disable

namespace WarehouseManagement.BalanceManagement.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250807134708_BalanceManagement_Initial")]
    partial class BalanceManagement_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("balance-management")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarehouseManagement.BalanceManagement.Domain.Entities.Balance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.ComplexProperty<Dictionary<string, object>>("ResourceId", "WarehouseManagement.BalanceManagement.Domain.Entities.Balance.ResourceId#ResourceId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("ResourceId");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ResourceStock", "WarehouseManagement.BalanceManagement.Domain.Entities.Balance.ResourceStock#Stock", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("ResourceStock");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UnitId", "WarehouseManagement.BalanceManagement.Domain.Entities.Balance.UnitId#UnitId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("UnitId");
                        });

                    b.HasKey("Id");

                    b.ToTable("Balances", "balance-management");
                });
#pragma warning restore 612, 618
        }
    }
}
