// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseManagement.IncomeProcessing.Infrastructure.DbContexts;

#nullable disable

namespace WarehouseManagement.IncomeProcessing.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250802175459_IncomeProcessing_Initial")]
    partial class IncomeProcessing_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("income-processing")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarehouseManagement.IncomeProcessing.Domain.Aggregates.IncomeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.ComplexProperty<Dictionary<string, object>>("CreatedAt", "WarehouseManagement.IncomeProcessing.Domain.Aggregates.IncomeDocument.CreatedAt#CreatedAt", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("NumDocument", "WarehouseManagement.IncomeProcessing.Domain.Aggregates.IncomeDocument.NumDocument#NumDocument", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("NumDocument");
                        });

                    b.HasKey("Id");

                    b.ToTable("IncomeDocuments", "income-processing");
                });

            modelBuilder.Entity("WarehouseManagement.IncomeProcessing.Domain.Entities.IncomeResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("IncomeDocumentId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("ResourceId", "WarehouseManagement.IncomeProcessing.Domain.Entities.IncomeResource.ResourceId#ResourceId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("ResourceId");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ResourceStock", "WarehouseManagement.IncomeProcessing.Domain.Entities.IncomeResource.ResourceStock#Stock", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("ResourceStock");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UnitId", "WarehouseManagement.IncomeProcessing.Domain.Entities.IncomeResource.UnitId#UnitId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("UnitId");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IncomeDocumentId");

                    b.ToTable("IncomeResources", "income-processing");
                });

            modelBuilder.Entity("WarehouseManagement.IncomeProcessing.Domain.Entities.IncomeResource", b =>
                {
                    b.HasOne("WarehouseManagement.IncomeProcessing.Domain.Aggregates.IncomeDocument", null)
                        .WithMany("Resources")
                        .HasForeignKey("IncomeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarehouseManagement.IncomeProcessing.Domain.Aggregates.IncomeDocument", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
